all:
#	g++ -o test test.cpp -lmysqlclient -L/usr/lib64/mysql -I/usr/include/mysql -lmysqlpp -L/usr/lib64 -I/usr/include/mysql++
#	g++ -o example example.cpp jsoncpp.cpp -I. -DJSON_IS_AMALGAMATION
	g++ -o test test.cpp jsoncpp.cpp -I/usr/include/mysql -I/usr/include/mysql++ -L/usr/lib64/mysql -L/usr/lib64 -lmysqlpp -lmysqlclient -I. -DJOSON_IS_AMALGAMATION

